// <auto-generated />
using System;
using IpmsSmartAssistant.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpmsSmartAssistant.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914162916_SeedNewManuals")]
    partial class SeedNewManuals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("IpmsSmartAssistant.Api.Models.KnowledgeBaseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBaseEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "1. Immediately check the physical pressure gauge.\n2. If pressure exceeds 15 bar, manually open the safety release valve.\n3. Shut down the main burner.\n4. Inspect the pressure sensor wiring for loose connections before restarting.",
                            Keywords = "boiler",
                            Title = "Boiler Pressure Fault"
                        },
                        new
                        {
                            Id = 2,
                            Content = "1. Ensure the weighbridge platform is completely empty and clean.\n2. Access the admin terminal and enter calibration mode.\n3. Perform a zero-point calibration.\n4. Place standard test weights on the platform and verify the digital load cell readings match.",
                            Keywords = "weighbridge",
                            Title = "Weighbridge Calibration"
                        },
                        new
                        {
                            Id = 3,
                            Content = "1. Stop the conveyor motor immediately.\n2. Locate the tensioning bolts on the tail pulley.\n3. Adjust the bolt on the side the belt is rubbing against by 1/4 turn clockwise.\n4. Run the belt empty for 2 minutes to verify centering.",
                            Keywords = "conveyor",
                            Title = "Conveyor Belt Alignment"
                        });
                });

            modelBuilder.Entity("IpmsSmartAssistant.Api.Models.TelemetryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TelemetryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
