using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace IpmsSmartAssistant.Api.Services;

public class OllamaService
{
    private readonly HttpClient _httpClient;

    public OllamaService(HttpClient httpClient)
    {
        _httpClient = httpClient;
        _httpClient.BaseAddress = new Uri("http://localhost:11434");
        _httpClient.Timeout = TimeSpan.FromMinutes(3); // Allow time for vision processing
    }

    public async Task<string> GenerateTroubleshootingGuideAsync(string userPrompt, string? base64Image = null)
    {
        // 1. Create the request body anonymously (replaces OllamaRequest)
        var requestBody = new
        {
            model = string.IsNullOrEmpty(base64Image) ? "llama3" : "llava", // Auto-switches to vision model!
            prompt = userPrompt,
            stream = false,
            images = string.IsNullOrEmpty(base64Image) ? null : new[] { base64Image }
        };

        // 2. Serialize the request body into JSON
        var jsonContent = new StringContent(
            System.Text.Json.JsonSerializer.Serialize(requestBody),
            System.Text.Encoding.UTF8,
            "application/json"
        );

        // 3. Send it to Ollama
        var response = await _httpClient.PostAsync("/api/generate", jsonContent);
        response.EnsureSuccessStatusCode();

        var responseBody = await response.Content.ReadAsStringAsync();
        var result = System.Text.Json.JsonSerializer.Deserialize<OllamaResponse>(responseBody, new System.Text.Json.JsonSerializerOptions { PropertyNameCaseInsensitive = true });

        return result?.Response ?? "No response generated by local engine.";
    }

    private class OllamaRequest
    {
        [JsonPropertyName("model")]
        public string Model { get; set; } = string.Empty;

        [JsonPropertyName("prompt")]
        public string Prompt { get; set; } = string.Empty;

        [JsonPropertyName("stream")]
        public bool Stream { get; set; } = false;

        [JsonPropertyName("images")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<string>? Images { get; set; }
    }

    private class OllamaResponse
    {
        [JsonPropertyName("response")]
        public string Response { get; set; } = string.Empty;
    }
}