using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace IpmsSmartAssistant.Api.Services;

public class OllamaService
{
    private readonly HttpClient _httpClient;

    public OllamaService(HttpClient httpClient)
    {
        _httpClient = httpClient;
        _httpClient.BaseAddress = new Uri("http://localhost:11434");
        _httpClient.Timeout = TimeSpan.FromMinutes(3); // Allow time for vision processing
    }

    public async Task<string> GenerateTroubleshootingGuideAsync(string userPrompt, string? base64Image = null)
    {
        var requestPayload = new OllamaRequest
        {
            Model = "llava", // uses your installed local model
            Prompt = userPrompt,
            Stream = false,
            Images = string.IsNullOrEmpty(base64Image) ? null : new List<string> { base64Image }
        };

        var jsonContent = new StringContent(
            JsonSerializer.Serialize(requestPayload),
            Encoding.UTF8,
            "application/json"
        );

        var response = await _httpClient.PostAsync("/api/generate", jsonContent);
        response.EnsureSuccessStatusCode();

        var responseBody = await response.Content.ReadAsStringAsync();
        var result = JsonSerializer.Deserialize<OllamaResponse>(responseBody);

        return result?.Response ?? "No response generated by local engine.";
    }

    private class OllamaRequest
    {
        [JsonPropertyName("model")]
        public string Model { get; set; } = string.Empty;

        [JsonPropertyName("prompt")]
        public string Prompt { get; set; } = string.Empty;

        [JsonPropertyName("stream")]
        public bool Stream { get; set; } = false;

        [JsonPropertyName("images")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public List<string>? Images { get; set; }
    }

    private class OllamaResponse
    {
        [JsonPropertyName("response")]
        public string Response { get; set; } = string.Empty;
    }
}